<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lorenna Diniz Dantas">

<title>Aplicação de Modelos ARIMA e SARIMA em Séries Temporais</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="projeto-2_files/libs/clipboard/clipboard.min.js"></script>
<script src="projeto-2_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="projeto-2_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="projeto-2_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="projeto-2_files/libs/quarto-html/popper.min.js"></script>
<script src="projeto-2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="projeto-2_files/libs/quarto-html/anchor.min.js"></script>
<link href="projeto-2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="projeto-2_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="projeto-2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="projeto-2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="projeto-2_files/libs/bootstrap/bootstrap-4d7f0bce1131f3e5f9547cd857cfbfc8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>
<script src="projeto-2_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="projeto-2_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sumário</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">1</span> Introdução</a></li>
  <li><a href="#análises" id="toc-análises" class="nav-link" data-scroll-target="#análises"><span class="header-section-number">2</span> Análises</a>
  <ul class="collapse">
  <li><a href="#série-1-taxa-de-variação-real-do-consumo-nos-lares-sarima" id="toc-série-1-taxa-de-variação-real-do-consumo-nos-lares-sarima" class="nav-link" data-scroll-target="#série-1-taxa-de-variação-real-do-consumo-nos-lares-sarima"><span class="header-section-number">2.1</span> Série 1: Taxa de Variação Real do Consumo nos Lares (SARIMA)</a></li>
  <li><a href="#série-2-ipca-taxa-de-variação-acumulada-em-12-meses-arima" id="toc-série-2-ipca-taxa-de-variação-acumulada-em-12-meses-arima" class="nav-link" data-scroll-target="#série-2-ipca-taxa-de-variação-acumulada-em-12-meses-arima"><span class="header-section-number">2.2</span> Série 2: IPCA — Taxa de Variação Acumulada em 12 Meses (ARIMA)</a></li>
  </ul></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão"><span class="header-section-number">3</span> Conclusão</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Aplicação de Modelos ARIMA e SARIMA em Séries Temporais</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lorenna Diniz Dantas </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introdução" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução"><span class="header-section-number">1</span> Introdução</h2>
<p>A análise de séries temporais desempenha um papel fundamental na compreensão de fenômenos econômicos ao longo do tempo, permitindo identificar padrões, tendências e comportamentos sazonais que auxiliam na tomada de decisão. Nesse contexto, modelos estatísticos como o ARIMA (AutoRegressive Integrated Moving Average) e o SARIMA (Seasonal ARIMA) destacam-se por sua capacidade de modelar estruturas temporais, incorporando componentes de tendência, autocorrelação e sazonalidade. Esses modelos são amplamente utilizados para previsão e interpretação de séries econômicas, especialmente quando se busca compreender a dinâmica de indicadores que variam ao longo do tempo sob influência de fatores estruturais e conjunturais.</p>
<p>O consumo nos lares, enquanto indicador-chave do desempenho do varejo alimentar, reflete diretamente o comportamento das famílias frente às condições econômicas. Variáveis como inflação, renda disponível, nível de emprego e expectativas influenciam significativamente os padrões de consumo, que, por sua vez, apresentam forte componente sazonal ao longo do ano. A análise da Taxa de Variação Real do Consumo dos Lares, disponibilizada pela Associação Brasileira de Supermercados (Abras), permite captar essas oscilações, sendo a série devidamente deflacionada pelo Índice de Preços ao Consumidor Amplo (IPCA). Diante da presença de sazonalidade bem definida, a aplicação de modelos SARIMA torna-se adequada para capturar tanto os padrões periódicos quanto os movimentos de curto prazo, contribuindo para previsões mais precisas e uma melhor interpretação do comportamento do consumo.</p>
<p>Por outro lado, a dinâmica da inflação no Brasil pode ser analisada por meio do Índice Nacional de Preços ao Consumidor Amplo (IPCA), principal indicador oficial utilizado no sistema de metas de inflação adotado pelo Banco Central do Brasil desde 1999. O IPCA mede a variação de preços de um conjunto de bens e serviços consumidos pelas famílias com rendimento entre 1 e 40 salários mínimos, abrangendo cerca de 90% das famílias urbanas. A série utilizada neste estudo corresponde à variação acumulada em 12 meses, o que permite observar a evolução da inflação em termos anuais, suavizando flutuações de curto prazo. Diferentemente de séries com forte componente sazonal mensal, essa transformação reduz significativamente a sazonalidade, destacando a tendência e a persistência inflacionária ao longo do tempo. Nesse contexto, modelos ARIMA mostram-se adequados para capturar a estrutura temporal da inflação, especialmente sua inércia e dependência serial.</p>
<p>Diante disso, vem a necessidade de conhecer os modelos estatísticos para modelar e prever adequadamente séries econômicas com características distintas, utilizando ferramentas estatísticas apropriadas, nesse caso o R. Dessa forma, o objetivo dessa análise não é apenas ajustar modelos adequados a cada contexto, mas também evidenciar a importância da escolha metodológica, contribuindo para uma compreensão mais precisa dos fenômenos econômicos e para a geração de previsões confiáveis.</p>
</section>
<section id="análises" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="análises"><span class="header-section-number">2</span> Análises</h2>
<hr>
<section id="série-1-taxa-de-variação-real-do-consumo-nos-lares-sarima" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="série-1-taxa-de-variação-real-do-consumo-nos-lares-sarima"><span class="header-section-number">2.1</span> Série 1: Taxa de Variação Real do Consumo nos Lares (SARIMA)</h3>
<p>A <strong>Taxa de Variação Real do Consumo nos Lares</strong> é um indicador mensal disponibilizado pela Associação Brasileira de Supermercados (ABRAS), deflacionado pelo IPCA. Ela mede a variação percentual mensal do consumo real das famílias nos supermercados brasileiros. Por refletir comportamentos sazonais típicos — como aumento do consumo em dezembro e queda em janeiro —, esta série é um caso clássico para a aplicação do modelo <strong>SARIMA</strong>.</p>
<section id="análise-descritiva" class="level4" data-number="2.1.1">
<h4 data-number="2.1.1" class="anchored" data-anchor-id="análise-descritiva"><span class="header-section-number">2.1.1</span> Análise Descritiva</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Estatísticas Descritivas — Consumo nos Lares (% a.m.)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mínimo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Máximo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Média</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Desvio Padrão</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">60</td>
<td style="text-align: right;">-22.01</td>
<td style="text-align: right;">22.47</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">1.74</td>
<td style="text-align: right;">8.17</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A série possui 60 observações mensais. A variação vai de -22.01% (quedas acentuadas em janeiro) a 22.47% (picos em dezembro). A média próxima de zero indica que, ao longo do tempo, as variações positivas e negativas se equilibram. O desvio padrão elevado confirma a grande oscilação mensal, característica esperada em séries com forte sazonalidade anual.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/plot-consumo-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico evidencia a <strong>sazonalidade</strong> da série, com picos recorrentes em dezembro — impulsionados pelo 13º salário e pelo maior volume de compras natalinas — e quedas acentuadas em janeiro. Esse padrão se repete a cada 12 meses de forma regular ao longo de todo o período. Não há tendência de longo prazo: a série oscila em torno de zero, sugerindo que o nível médio do consumo real se manteve estável ao longo do tempo.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/grafico-sazonal-consumo-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico sazonal sobrepõe as trajetórias de cada ano, tornando o padrão repetitivo visualmente evidente: dezembro concentra consistentemente os maiores valores, enquanto janeiro concentra as maiores quedas. A regularidade com que esse ciclo se repete a cada 12 meses confirma a presença de forte sazonalidade anual e motiva o uso de modelos SARIMA.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/subseries-consumo-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico de subséries exibe a série de cada mês separadamente ao longo dos anos. A linha horizontal em cada painel representa a média histórica daquele mês. Dezembro apresenta média muito acima de todos os demais meses, enquanto janeiro apresenta média muito abaixo, reforçando a estrutura sazonal de período 12. A relativa estabilidade das médias ao longo dos anos indica ausência de mudança estrutural no padrão sazonal.</p>
</section>
<section id="análise-da-acf-e-pacf" class="level4" data-number="2.1.2">
<h4 data-number="2.1.2" class="anchored" data-anchor-id="análise-da-acf-e-pacf"><span class="header-section-number">2.1.2</span> Análise da ACF e PACF</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/ACF-PACF-consumo-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A <strong>ACF</strong> (Função de Autocorrelação) apresenta picos significativos nos lags múltiplos de 12 (12, 24, 36), confirmando a sazonalidade anual. O padrão oscilatório — em vez de decaimento suave — é típico de séries com componente sazonal dominante. Esse resultado indica a necessidade de diferenciação sazonal (<span class="math inline">\(D = 1\)</span>, <span class="math inline">\(s = 12\)</span>) antes do ajuste do modelo.</p>
<p>A <strong>PACF</strong> (Função de Autocorrelação Parcial), que mede a correlação direta entre observações separadas por <span class="math inline">\(k\)</span> lags controlando os intermediários, exibe pico muito pronunciado no lag 12 e decaimento rápido nos demais, evidenciando forte dependência sazonal direta de ordem 1. Isso sugere a presença de um componente autorregressivo sazonal (<span class="math inline">\(P = 1\)</span>) na estrutura do modelo.</p>
</section>
<section id="teste-de-estacionariedade" class="level4" data-number="2.1.3">
<h4 data-number="2.1.3" class="anchored" data-anchor-id="teste-de-estacionariedade"><span class="header-section-number">2.1.3</span> Teste de Estacionariedade</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Teste KPSS — Consumo nos Lares (série original)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">kpss_stat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">kpss_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.2381</td>
<td style="text-align: right;">0.1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>O <strong>teste KPSS</strong> (Kwiatkowski-Phillips-Schmidt-Shin) avalia a hipótese nula (<span class="math inline">\(H_0\)</span>) de que a série é estacionária em torno de uma média ou tendência. Um p-valor <span class="math inline">\(\leq 0{,}05\)</span> leva à rejeição de <span class="math inline">\(H_0\)</span>, indicando não estacionariedade. O resultado obtido (<span class="math inline">\(p\text{-valor} = 0{,}10 &gt; 0{,}05\)</span>) indica que <strong>não rejeitamos</strong> <span class="math inline">\(H_0\)</span>: a série pode ser considerada estacionária em nível, sem tendência determinística significativa (<span class="math inline">\(d = 0\)</span>).</p>
<p>É importante ressaltar, contudo, que o KPSS detecta tendência, e não sazonalidade. Portanto, mesmo com a série estacionária em nível, a forte estrutura sazonal identificada na ACF e PACF exige a aplicação de <strong>diferenciação sazonal</strong> (<span class="math inline">\(D = 1\)</span>) para adequar a série à modelagem SARIMA.</p>
</section>
<section id="diferenciação-sazonal" class="level4" data-number="2.1.4">
<h4 data-number="2.1.4" class="anchored" data-anchor-id="diferenciação-sazonal"><span class="header-section-number">2.1.4</span> Diferenciação Sazonal</h4>
<p>Para remover o padrão sazonal de 12 meses, aplica-se a diferenciação sazonal (<span class="math inline">\(D = 1\)</span>, <span class="math inline">\(s = 12\)</span>). Como o teste KPSS não indicou necessidade de diferenciação regular, mantemos <span class="math inline">\(d = 0\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/diferenciacao-consumo-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Após a diferenciação sazonal (<span class="math inline">\(D = 1\)</span>, <span class="math inline">\(s = 12\)</span>), a série passa a oscilar em torno de zero com variância aproximadamente constante e sem padrão sazonal visível, comportamento consistente com estacionariedade.</p>
<p>Na <strong>ACF diferenciada</strong>, picos nos primeiros lags e no lag 12 sugerem componente MA(1) não sazonal e MA(1) sazonal (<span class="math inline">\(Q = 1\)</span>). Na <strong>PACF diferenciada</strong>, o pico mais relevante ocorre no lag 1, sugerindo a presença de componente AR(1) não sazonal (<span class="math inline">\(p = 1\)</span>). O lag 12 da PACF, com pico significativo, reforça o componente AR sazonal (<span class="math inline">\(P = 1\)</span>) já identificado anteriormente. Esses padrões orientam a especificação dos candidatos SARIMA.</p>
</section>
<section id="teste-kpss-após-diferenciação-sazonal" class="level4" data-number="2.1.5">
<h4 data-number="2.1.5" class="anchored" data-anchor-id="teste-kpss-após-diferenciação-sazonal"><span class="header-section-number">2.1.5</span> Teste KPSS Após Diferenciação Sazonal</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Teste KPSS — Consumo após diferenciação sazonal (D=1, s=12)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">kpss_stat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">kpss_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.1605</td>
<td style="text-align: right;">0.1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Após a diferenciação sazonal, o p-valor obtido é <span class="math inline">\(&gt; 0{,}05\)</span>, confirmando que <strong>não rejeitamos</strong> <span class="math inline">\(H_0\)</span> de estacionariedade. A série diferenciada sazonalmente é, portanto, estacionária, o que valida o uso de <span class="math inline">\(d = 0\)</span> e <span class="math inline">\(D = 1\)</span> no modelo SARIMA. Não há necessidade de aplicar diferenciação regular adicional.</p>
</section>
<section id="separação-treino-e-teste" class="level4" data-number="2.1.6">
<h4 data-number="2.1.6" class="anchored" data-anchor-id="separação-treino-e-teste"><span class="header-section-number">2.1.6</span> Separação Treino e Teste</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Período de treinamento: 2021 jan a 2024 out </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Período de teste: 2024 nov a 2025 dez </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Observações treino: 46 | Observações teste: 14 </code></pre>
</div>
</div>
<p>Os dados são divididos em <strong>conjunto de treino</strong> — utilizado para estimar os parâmetros dos modelos — e <strong>conjunto de teste</strong> — reservado exclusivamente para avaliação das previsões fora da amostra. Os meses finais da série compõem o conjunto de teste, simulando uma situação real de previsão em que os valores futuros são desconhecidos no momento do ajuste.</p>
</section>
<section id="ajuste-e-comparação-de-modelos-sarima" class="level4" data-number="2.1.7">
<h4 data-number="2.1.7" class="anchored" data-anchor-id="ajuste-e-comparação-de-modelos-sarima"><span class="header-section-number">2.1.7</span> Ajuste e Comparação de Modelos SARIMA</h4>
<p>Com base na análise da ACF e PACF da série diferenciada sazonalmente, foram especificados manualmente sete modelos candidatos SARIMA<span class="math inline">\((p, d, q)(P, D, Q)_{12}\)</span> e incluída a seleção automática por busca exaustiva como referência.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Critérios de Seleção de Modelos SARIMA — Consumo nos Lares</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">log_lik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AICc</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sarima002_110</td>
<td style="text-align: right;">13.900</td>
<td style="text-align: right;">-92.389</td>
<td style="text-align: right;">192.778</td>
<td style="text-align: right;">194.157</td>
<td style="text-align: right;">198.883</td>
</tr>
<tr class="even">
<td style="text-align: left;">auto</td>
<td style="text-align: right;">13.900</td>
<td style="text-align: right;">-92.389</td>
<td style="text-align: right;">192.778</td>
<td style="text-align: right;">194.157</td>
<td style="text-align: right;">198.883</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sarima100_110</td>
<td style="text-align: right;">14.675</td>
<td style="text-align: right;">-93.869</td>
<td style="text-align: right;">193.737</td>
<td style="text-align: right;">194.537</td>
<td style="text-align: right;">198.316</td>
</tr>
<tr class="even">
<td style="text-align: left;">sarima300_110</td>
<td style="text-align: right;">14.254</td>
<td style="text-align: right;">-92.163</td>
<td style="text-align: right;">194.327</td>
<td style="text-align: right;">196.470</td>
<td style="text-align: right;">201.958</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sarima101_110</td>
<td style="text-align: right;">15.012</td>
<td style="text-align: right;">-93.696</td>
<td style="text-align: right;">195.392</td>
<td style="text-align: right;">196.772</td>
<td style="text-align: right;">201.498</td>
</tr>
<tr class="even">
<td style="text-align: left;">sarima001_110</td>
<td style="text-align: right;">15.613</td>
<td style="text-align: right;">-95.008</td>
<td style="text-align: right;">196.015</td>
<td style="text-align: right;">196.815</td>
<td style="text-align: right;">200.594</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sarima100_011</td>
<td style="text-align: right;">13.270</td>
<td style="text-align: right;">-96.692</td>
<td style="text-align: right;">199.383</td>
<td style="text-align: right;">200.211</td>
<td style="text-align: right;">203.873</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A comparação dos modelos foi realizada com base no <strong>AICc</strong> (Critério de Informação de Akaike corrigido para amostras finitas), que penaliza a complexidade do modelo e favorece estruturas mais parcimoniosas. A tabela acima está ordenada do melhor (menor AICc) para o pior candidato.</p>
<p>O modelo <strong>SARIMA(0,0,2)(1,1,0)</strong><span class="math inline">\(_{12}\)</span> apresentou os menores valores de AIC, AICc e BIC, sendo identificado tanto pela seleção automática quanto pela comparação manual como a estrutura mais adequada. Ele incorpora dois termos de média móvel não sazonal (<span class="math inline">\(q = 2\)</span>) para capturar dependências de curto prazo, além de um componente autorregressivo sazonal (<span class="math inline">\(P = 1\)</span>), refletindo a influência do consumo observado no mesmo mês do ano anterior. A diferenciação sazonal (<span class="math inline">\(D = 1\)</span>) mostrou-se suficiente para tornar a série estacionária, sem necessidade de diferenciação regular.</p>
<p>Alguns modelos especificados manualmente retornaram <code>&lt;NULL model&gt;</code>, indicando falha de convergência ou inadequação estrutural aos dados, o que reforça a importância de combinar a análise dos correlogramas com a comparação por critérios de informação.</p>
</section>
<section id="diagnóstico-dos-resíduos" class="level4" data-number="2.1.8">
<h4 data-number="2.1.8" class="anchored" data-anchor-id="diagnóstico-dos-resíduos"><span class="header-section-number">2.1.8</span> Diagnóstico dos Resíduos</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/residuos-consumo-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O diagnóstico dos resíduos do modelo SARIMA<span class="math inline">\((0,0,2)(1,1,0)_{12}\)</span> avalia se o modelo capturou toda a estrutura temporal da série.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Teste de Ljung-Box — Resíduos do sarima002_110 (Consumo nos Lares)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lb_stat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sarima002_110</td>
<td style="text-align: right;">19.9062</td>
<td style="text-align: right;">0.5889</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>O <strong>teste de Ljung-Box</strong> avalia formalmente a hipótese nula (<span class="math inline">\(H_0\)</span>) de que os resíduos são não autocorrelacionados até o lag 24. O p-valor obtido é <span class="math inline">\(&gt; 0{,}05\)</span>, portanto <strong>não rejeitamos</strong> <span class="math inline">\(H_0\)</span>: os resíduos não apresentam autocorrelação residual significativa, confirmando que o modelo capturou toda a estrutura temporal da série. O resultado valida o modelo SARIMA<span class="math inline">\((0,0,2)(1,1,0)_{12}\)</span> como adequado para descrever a dinâmica do consumo nos lares.</p>
</section>
<section id="previsão" class="level4" data-number="2.1.9">
<h4 data-number="2.1.9" class="anchored" data-anchor-id="previsão"><span class="header-section-number">2.1.9</span> Previsão</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/consumo-forecast-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico compara as previsões geradas pelo modelo SARIMA com os valores efetivamente observados no conjunto de teste (linha vermelha). O modelo preserva o padrão sazonal esperado: as previsões reproduzem corretamente a queda em janeiro e o pico em dezembro. Os valores reais encontram-se majoritariamente dentro dos intervalos de confiança de 80% e 95%, indicando boa calibração do modelo.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Métricas de Acurácia das Previsões — sarima002_110 | Consumo nos Lares</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">RMSE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MAE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MAPE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sarima002_110</td>
<td style="text-align: right;">3.4565</td>
<td style="text-align: right;">2.6354</td>
<td style="text-align: right;">82.7633</td>
<td style="text-align: right;">0.7459</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As métricas de acurácia confirmam o desempenho do modelo no conjunto de teste.</p>
<hr>
</section>
</section>
<section id="série-2-ipca-taxa-de-variação-acumulada-em-12-meses-arima" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="série-2-ipca-taxa-de-variação-acumulada-em-12-meses-arima"><span class="header-section-number">2.2</span> Série 2: IPCA — Taxa de Variação Acumulada em 12 Meses (ARIMA)</h3>
<p>O <strong>IPCA (Índice de Preços ao Consumidor Amplo)</strong> é calculado mensalmente pelo IBGE e constitui o indicador oficial da inflação brasileira, utilizado pelo Banco Central para o regime de metas de inflação. A série analisada corresponde à <strong>taxa de variação acumulada em 12 meses (% a.a.)</strong>, disponibilizada pelo Ipea, com registros a partir de julho de 1994. Ela captura a intensidade inflacionária em cada momento, incorporando os efeitos de choques de oferta, políticas monetárias e câmbio. A análise se concentra no período <strong>pós-Plano Real (a partir de julho de 1994)</strong>, quando a série passa a apresentar comportamento mais estável e adequado à modelagem por <strong>ARIMA</strong>.</p>
<section id="preparação-dos-dados" class="level4" data-number="2.2.1">
<h4 data-number="2.2.1" class="anchored" data-anchor-id="preparação-dos-dados"><span class="header-section-number">2.2.1</span> Preparação dos Dados</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Período analisado: 1994 jul a 2026 fev </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Total de observações: 380 </code></pre>
</div>
</div>
</section>
<section id="análise-descritiva-1" class="level4" data-number="2.2.2">
<h4 data-number="2.2.2" class="anchored" data-anchor-id="análise-descritiva-1"><span class="header-section-number">2.2.2</span> Análise Descritiva</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Estatísticas Descritivas — IPCA (% a.a. acumulado em 12 meses)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mínimo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Máximo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Média</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Desvio Padrão</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">380</td>
<td style="text-align: right;">1.65</td>
<td style="text-align: right;">4005.08</td>
<td style="text-align: right;">45.5</td>
<td style="text-align: right;">5.92</td>
<td style="text-align: right;">306.77</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A análise descritiva evidencia importantes características da série. A <strong>média</strong> é substancialmente superior à <strong>mediana</strong>, indicando forte assimetria positiva. A distribuição é puxada para cima por valores extremamente altos no início do período, correspondentes à inflação elevada logo após o Plano Real. O <strong>máximo</strong> superior a 4000 reforça essa evidência, ao passo que o <strong>desvio padrão</strong> elevado reflete a grande dispersão causada por esses extremos históricos. Após a estabilização monetária, o comportamento da série se torna consideravelmente diferente, com inflação oscilando em níveis bem mais baixos, o que justifica a atenção especial ao tratamento dos valores iniciais nas etapas seguintes.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/serie-ipca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A série revela uma queda abrupta nos níveis de inflação no início do período, correspondente ao impacto do Plano Real na estabilização econômica. Após essa transição, a série passa a oscilar em torno de níveis significativamente mais baixos e relativamente estáveis. Não se observa padrão sazonal regular ao longo do tempo, em razão da transformação acumulada em 12 meses, que suaviza as variações mensais. Nota-se, porém, certa <strong>persistência inflacionária</strong>, pois a série tende a permanecer elevada por períodos prolongados antes de recuar, e vice-versa, que é uma característica de inércia inflacionária e justifica o uso de modelos ARIMA para capturar essa dependência temporal.</p>
</section>
<section id="análise-da-acf-e-pacf-1" class="level4" data-number="2.2.3">
<h4 data-number="2.2.3" class="anchored" data-anchor-id="análise-da-acf-e-pacf-1"><span class="header-section-number">2.2.3</span> Análise da ACF e PACF</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/ACF-PACF-ipca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A <strong>ACF</strong> apresenta decaimento extremamente lento e persistente, com autocorrelações significativas por dezenas de lags. Esse é o padrão clássico de <strong>não estacionariedade</strong>: a série possui memória longa, com observações altamente correlacionadas com suas versões defasadas mesmo em horizontes distantes — comportamento típico quando há tendência ou persistência de longo prazo.</p>
<p>A <strong>PACF</strong> exibe um pico muito pronunciado no lag 1 seguido de decaimento rápido. Esse padrão sugere que, após a diferenciação, a estrutura de dependência residual pode ser bem descrita por um componente <strong>AR(1)</strong>: a observação de um período é fortemente influenciada pela imediatamente anterior, mas a correlação direta desaparece rapidamente para lags maiores.</p>
</section>
<section id="teste-de-estacionariedade-1" class="level4" data-number="2.2.4">
<h4 data-number="2.2.4" class="anchored" data-anchor-id="teste-de-estacionariedade-1"><span class="header-section-number">2.2.4</span> Teste de Estacionariedade</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Teste KPSS — IPCA (série original)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">kpss_stat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">kpss_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.559</td>
<td style="text-align: right;">0.0284</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>O teste KPSS aplicado à série original resulta em p-valor <span class="math inline">\(&lt; 0{,}05\)</span>, levando à <strong>rejeição de</strong> <span class="math inline">\(H_0\)</span> de estacionariedade. Mesmo visualmente a série exibir certa estabilidade após o Plano Real, a presença dos valores iniciais muito elevados e a persistência inflacionária tornam a série globalmente não estacionária. Isso confirma a necessidade de diferenciação antes do ajuste do modelo ARIMA.</p>
</section>
<section id="diferenciação" class="level4" data-number="2.2.5">
<h4 data-number="2.2.5" class="anchored" data-anchor-id="diferenciação"><span class="header-section-number">2.2.5</span> Diferenciação</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/diferenciacao-ipca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Após a primeira diferença (<span class="math inline">\(d = 1\)</span>), a série passa a oscilar em torno de zero com amplitude mais controlada, indicando remoção da tendência de longo prazo. No entanto, o início da série ainda apresenta variações muito bruscas, reflexo dos valores extremos do período imediatamente pós-Plano Real, que persistem como influência na série diferenciada.</p>
<p>Na <strong>ACF diferenciada</strong>, observa-se corte relativamente abrupto após os primeiros lags, sem picos sazonais evidentes, sugerindo um processo de baixa ordem, possivelmente MA(1) ou MA(2). Na <strong>PACF diferenciada</strong>, pico no lag 1 com decaimento rápido reforça a hipótese de AR(1) ou AR(2) após a diferenciação. A ausência de padrão sazonal nos correlogramas confirma que o modelo adequado é ARIMA, sem componente sazonal explícito.</p>
</section>
<section id="teste-kpss-após-diferenciação" class="level4" data-number="2.2.6">
<h4 data-number="2.2.6" class="anchored" data-anchor-id="teste-kpss-após-diferenciação"><span class="header-section-number">2.2.6</span> Teste KPSS Após Diferenciação</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Teste KPSS — IPCA (após 1ª diferenciação)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">kpss_stat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">kpss_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.5845</td>
<td style="text-align: right;">0.024</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>O teste KPSS aplicado à série diferenciada ainda resulta em p-valor <span class="math inline">\(&lt; 0{,}05\)</span>, levando à rejeição de <span class="math inline">\(H_0\)</span>. Isso indica que <strong>a primeira diferenciação não foi suficiente</strong> para tornar a série completamente estacionária. Esse resultado é fortemente influenciado pelos valores extremos no início da amostra — os choques inflacionários do início do Plano Real — que geram variações abruptas na série diferenciada e impedem o estabelecimento de um comportamento estacionário global. Essa limitação motivará o uso de abordagens complementares, como o tratamento de outliers, nas etapas seguintes.</p>
</section>
<section id="separação-treino-e-teste-1" class="level4" data-number="2.2.7">
<h4 data-number="2.2.7" class="anchored" data-anchor-id="separação-treino-e-teste-1"><span class="header-section-number">2.2.7</span> Separação Treino e Teste</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Período de treinamento: 1994 jul a 2024 dez </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Período de teste: 2025 jan a 2026 fev </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Observações treino: 366 | Observações teste: 14 </code></pre>
</div>
</div>
<p>Os dados são divididos em <strong>treino</strong> (até dezembro de 2024) e <strong>teste</strong> (janeiro de 2025 em diante), seguindo a mesma lógica de avaliação fora da amostra adotada para a série de consumo.</p>
</section>
<section id="ajuste-e-comparação-de-modelos-arima" class="level4" data-number="2.2.8">
<h4 data-number="2.2.8" class="anchored" data-anchor-id="ajuste-e-comparação-de-modelos-arima"><span class="header-section-number">2.2.8</span> Ajuste e Comparação de Modelos ARIMA</h4>
<p>Com base na análise dos correlogramas da série diferenciada, foram especificados seis modelos candidatos ARIMA<span class="math inline">\((p, d, q)\)</span> e incluída a seleção automática como referência.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Critérios de Seleção de Modelos ARIMA — IPCA (% a.a.)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">log_lik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AICc</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">auto</td>
<td style="text-align: right;">60.553</td>
<td style="text-align: right;">-1266.187</td>
<td style="text-align: right;">2546.375</td>
<td style="text-align: right;">2546.689</td>
<td style="text-align: right;">2573.655</td>
</tr>
<tr class="even">
<td style="text-align: left;">arima_210</td>
<td style="text-align: right;">77.545</td>
<td style="text-align: right;">-1311.676</td>
<td style="text-align: right;">2635.353</td>
<td style="text-align: right;">2635.587</td>
<td style="text-align: right;">2658.752</td>
</tr>
<tr class="odd">
<td style="text-align: left;">arima_012</td>
<td style="text-align: right;">713.559</td>
<td style="text-align: right;">-1718.811</td>
<td style="text-align: right;">3447.623</td>
<td style="text-align: right;">3447.790</td>
<td style="text-align: right;">3467.122</td>
</tr>
<tr class="even">
<td style="text-align: left;">arima_110</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: right;">-134.096</td>
<td style="text-align: right;">3467.571</td>
<td style="text-align: right;">3467.739</td>
<td style="text-align: right;">3487.071</td>
</tr>
<tr class="odd">
<td style="text-align: left;">arima_111</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: right;">-134.022</td>
<td style="text-align: right;">3469.425</td>
<td style="text-align: right;">3469.660</td>
<td style="text-align: right;">3492.824</td>
</tr>
<tr class="even">
<td style="text-align: left;">arima_011</td>
<td style="text-align: right;">0.133</td>
<td style="text-align: right;">-160.747</td>
<td style="text-align: right;">3520.874</td>
<td style="text-align: right;">3521.041</td>
<td style="text-align: right;">3540.373</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rw_drift</td>
<td style="text-align: right;">6336.158</td>
<td style="text-align: right;">-2113.514</td>
<td style="text-align: right;">4237.029</td>
<td style="text-align: right;">4237.196</td>
<td style="text-align: right;">4256.528</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A tabela compara os modelos candidatos pelo <strong>AICc</strong>, do melhor para o pior. O modelo <code>rw_drift</code> (Random Walk com <em>drift</em>) serve como <strong>linha de base</strong>: representa a hipótese de que a inflação segue uma caminhada aleatória com tendência linear. Se modelos mais elaborados não o superarem, isso indicaria que a dinâmica do IPCA não possui estrutura de dependência temporal capturável além da simples tendência.</p>
<p>O modelo selecionado automaticamente — identificado programaticamente a seguir — tende a apresentar ordem elevada de diferenciação e/ou autorregressão, reflexo da persistência e dos choques extremos no início da série.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Melhor modelo ARIMA para IPCA: auto </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: ipca 
Model: ARIMA(5,2,0)(0,0,1)[12] 

Coefficients:
         ar1     ar2     ar3     ar4      ar5     sma1
      0.6718  0.4594  0.1083  0.5056  -0.7479  -0.5627
s.e.  0.0571  0.1427  0.0824  0.1165   0.0570      NaN

sigma^2 estimated as 60.55:  log likelihood=-1266.19
AIC=2546.37   AICc=2546.69   BIC=2573.65</code></pre>
</div>
</div>
<p>O modelo ARIMA selecionado indica que a série necessita de duas diferenciações para atingir estacionariedade (<span class="math inline">\(d = 2\)</span>) e que seu comportamento é fortemente influenciado por diversas defasagens passadas (parâmetro <span class="math inline">\(p\)</span> elevado). Essa estrutura complexa é consequência direta dos valores extremos presentes no início da amostra, que introduzem alta persistência e irregularidade na série. A variância dos erros (<span class="math inline">\(\sigma^2\)</span>) informa a magnitude típica dos erros de ajuste in-sample: quanto menor, melhor o ajuste.</p>
</section>
<section id="diagnóstico-dos-resíduos-1" class="level4" data-number="2.2.9">
<h4 data-number="2.2.9" class="anchored" data-anchor-id="diagnóstico-dos-resíduos-1"><span class="header-section-number">2.2.9</span> Diagnóstico dos Resíduos</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/residuos-ipca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A análise dos resíduos do modelo selecionado revela limitações importantes.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Teste de Ljung-Box — Resíduos do auto (IPCA)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lb_stat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">auto</td>
<td style="text-align: right;">208.1444</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>O teste de Ljung-Box confirma formalmente a presença de <strong>autocorrelação nos resíduos</strong> (p-valor <span class="math inline">\(&lt; 0{,}05\)</span>, rejeitando <span class="math inline">\(H_0\)</span>). Isso significa que o modelo não capturou adequadamente toda a estrutura temporal da série. A superdiferenciação (<span class="math inline">\(d = 2\)</span>), aliada à presença de outliers extremos no início da amostra, compromete tanto o ajuste quanto a capacidade preditiva do modelo. Esse diagnóstico motiva a adoção de abordagens alternativas, como o tratamento explícito dos outliers.</p>
</section>
<section id="previsão-1" class="level4" data-number="2.2.10">
<h4 data-number="2.2.10" class="anchored" data-anchor-id="previsão-1"><span class="header-section-number">2.2.10</span> Previsão</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/ipca-forecast-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A previsão do modelo ARIMA com dupla diferenciação apresenta comportamento problemático: os intervalos de confiança são <strong>excessivamente amplos</strong>, refletindo a alta incerteza gerada pela estrutura superdiferenciada. As previsões pontuais divergem do padrão recente da série, não reproduzindo a trajetória de inflação moderada observada nos últimos anos. Isso confirma que o modelo, apesar de ter o menor AICc entre os candidatos, <strong>não é adequado para fins preditivos</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Métricas de Acurácia das Previsões — auto | IPCA</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">RMSE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MAE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MAPE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">auto</td>
<td style="text-align: right;">10.512</td>
<td style="text-align: right;">7.5391</td>
<td style="text-align: right;">170.4089</td>
<td style="text-align: right;">0.1714</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As métricas de acurácia reforçam as limitações do modelo. O <strong>MAPE</strong> extremamente elevado evidencia grande erro relativo nas previsões, mesmo que o RMSE e o MAE em termos absolutos possam parecer aceitáveis. O <strong>MASE</strong> superior a 1 indica que o modelo <strong>não supera a previsão ingênua</strong>, ou seja, simplesmente repetir o último valor observado produziria previsões mais precisas. Esse resultado, combinado com a autocorrelação residual e a instabilidade das previsões, reforça a necessidade de uma abordagem alternativa que trate adequadamente os outliers presentes na série.</p>
</section>
<section id="tratamento-de-outliers" class="level4" data-number="2.2.11">
<h4 data-number="2.2.11" class="anchored" data-anchor-id="tratamento-de-outliers"><span class="header-section-number">2.2.11</span> Tratamento de Outliers</h4>
<p>Diante das limitações do modelo ARIMA tradicional — especialmente a influência desproporcionada dos valores extremos do início da série sobre o ajuste e as previsões —, foi adotada a estratégia de <strong>identificação, remoção e interpolação de outliers</strong> via decomposição STL.</p>
<p><strong>Decomposição STL</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/stl-ipca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A decomposição STL (Seasonal and Trend decomposition using Loess) separa a série em componentes de <strong>tendência</strong>, <strong>sazonalidade</strong> e <strong>resíduo</strong>. Como a série do IPCA acumulado em 12 meses não possui sazonalidade mensal expressiva, o componente sazonal é praticamente nulo e toda a variação de curto prazo é absorvida pelo resíduo. A análise do <strong>componente residual</strong> é, portanto, a ferramenta mais adequada para identificar observações atípicas: valores do resíduo muito afastados de zero correspondem a pontos da série que não são explicados pela tendência e que representam choques ou anomalias.</p>
<p><strong>Identificação dos Outliers</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Outliers identificados — Componente residual da decomposição STL</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">data_ym</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">ipca</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">trend</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">remainder</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1982 out</td>
<td style="text-align: right;">101.19</td>
<td style="text-align: right;">119.25</td>
<td style="text-align: right;">-18.06</td>
</tr>
<tr class="even">
<td style="text-align: left;">1982 nov</td>
<td style="text-align: right;">101.22</td>
<td style="text-align: right;">121.37</td>
<td style="text-align: right;">-20.15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1982 dez</td>
<td style="text-align: right;">104.79</td>
<td style="text-align: right;">123.64</td>
<td style="text-align: right;">-18.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">1983 jan</td>
<td style="text-align: right;">108.00</td>
<td style="text-align: right;">126.03</td>
<td style="text-align: right;">-18.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1983 fev</td>
<td style="text-align: right;">110.38</td>
<td style="text-align: right;">128.54</td>
<td style="text-align: right;">-18.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">1983 mar</td>
<td style="text-align: right;">113.63</td>
<td style="text-align: right;">131.17</td>
<td style="text-align: right;">-17.54</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1983 abr</td>
<td style="text-align: right;">115.03</td>
<td style="text-align: right;">133.93</td>
<td style="text-align: right;">-18.90</td>
</tr>
<tr class="even">
<td style="text-align: left;">1983 mai</td>
<td style="text-align: right;">114.67</td>
<td style="text-align: right;">136.80</td>
<td style="text-align: right;">-22.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1983 jun</td>
<td style="text-align: right;">120.24</td>
<td style="text-align: right;">139.78</td>
<td style="text-align: right;">-19.54</td>
</tr>
<tr class="even">
<td style="text-align: left;">1984 mai</td>
<td style="text-align: right;">189.03</td>
<td style="text-align: right;">175.46</td>
<td style="text-align: right;">13.57</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1984 nov</td>
<td style="text-align: right;">205.97</td>
<td style="text-align: right;">188.03</td>
<td style="text-align: right;">17.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">1984 dez</td>
<td style="text-align: right;">215.26</td>
<td style="text-align: right;">189.31</td>
<td style="text-align: right;">25.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1985 jan</td>
<td style="text-align: right;">221.27</td>
<td style="text-align: right;">190.41</td>
<td style="text-align: right;">30.86</td>
</tr>
<tr class="even">
<td style="text-align: left;">1985 fev</td>
<td style="text-align: right;">225.28</td>
<td style="text-align: right;">191.38</td>
<td style="text-align: right;">33.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1985 mar</td>
<td style="text-align: right;">228.93</td>
<td style="text-align: right;">192.24</td>
<td style="text-align: right;">36.69</td>
</tr>
<tr class="even">
<td style="text-align: left;">1985 abr</td>
<td style="text-align: right;">224.88</td>
<td style="text-align: right;">192.99</td>
<td style="text-align: right;">31.89</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1985 mai</td>
<td style="text-align: right;">219.36</td>
<td style="text-align: right;">193.65</td>
<td style="text-align: right;">25.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">1985 jun</td>
<td style="text-align: right;">214.76</td>
<td style="text-align: right;">194.30</td>
<td style="text-align: right;">20.46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1985 jul</td>
<td style="text-align: right;">216.44</td>
<td style="text-align: right;">194.98</td>
<td style="text-align: right;">21.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">1985 ago</td>
<td style="text-align: right;">224.26</td>
<td style="text-align: right;">195.70</td>
<td style="text-align: right;">28.56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1985 set</td>
<td style="text-align: right;">222.43</td>
<td style="text-align: right;">196.49</td>
<td style="text-align: right;">25.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">1985 out</td>
<td style="text-align: right;">222.95</td>
<td style="text-align: right;">197.37</td>
<td style="text-align: right;">25.58</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1985 nov</td>
<td style="text-align: right;">233.02</td>
<td style="text-align: right;">198.33</td>
<td style="text-align: right;">34.69</td>
</tr>
<tr class="even">
<td style="text-align: left;">1985 dez</td>
<td style="text-align: right;">242.23</td>
<td style="text-align: right;">199.36</td>
<td style="text-align: right;">42.87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1986 jan</td>
<td style="text-align: right;">250.23</td>
<td style="text-align: right;">200.43</td>
<td style="text-align: right;">49.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">1986 fev</td>
<td style="text-align: right;">256.08</td>
<td style="text-align: right;">201.54</td>
<td style="text-align: right;">54.54</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1986 mar</td>
<td style="text-align: right;">238.65</td>
<td style="text-align: right;">202.76</td>
<td style="text-align: right;">35.89</td>
</tr>
<tr class="even">
<td style="text-align: left;">1986 jun</td>
<td style="text-align: right;">178.52</td>
<td style="text-align: right;">208.79</td>
<td style="text-align: right;">-30.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1986 jul</td>
<td style="text-align: right;">156.80</td>
<td style="text-align: right;">212.16</td>
<td style="text-align: right;">-55.36</td>
</tr>
<tr class="even">
<td style="text-align: left;">1986 ago</td>
<td style="text-align: right;">137.33</td>
<td style="text-align: right;">216.54</td>
<td style="text-align: right;">-79.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1986 set</td>
<td style="text-align: right;">117.25</td>
<td style="text-align: right;">222.16</td>
<td style="text-align: right;">-104.91</td>
</tr>
<tr class="even">
<td style="text-align: left;">1986 out</td>
<td style="text-align: right;">100.13</td>
<td style="text-align: right;">229.09</td>
<td style="text-align: right;">-128.96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1986 nov</td>
<td style="text-align: right;">85.17</td>
<td style="text-align: right;">237.26</td>
<td style="text-align: right;">-152.09</td>
</tr>
<tr class="even">
<td style="text-align: left;">1986 dez</td>
<td style="text-align: right;">79.66</td>
<td style="text-align: right;">246.57</td>
<td style="text-align: right;">-166.91</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1987 jan</td>
<td style="text-align: right;">77.84</td>
<td style="text-align: right;">257.04</td>
<td style="text-align: right;">-179.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">1987 fev</td>
<td style="text-align: right;">77.71</td>
<td style="text-align: right;">268.73</td>
<td style="text-align: right;">-191.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1987 mar</td>
<td style="text-align: right;">97.39</td>
<td style="text-align: right;">281.73</td>
<td style="text-align: right;">-184.34</td>
</tr>
<tr class="even">
<td style="text-align: left;">1987 abr</td>
<td style="text-align: right;">133.27</td>
<td style="text-align: right;">296.12</td>
<td style="text-align: right;">-162.85</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1987 mai</td>
<td style="text-align: right;">179.40</td>
<td style="text-align: right;">311.94</td>
<td style="text-align: right;">-132.54</td>
</tr>
<tr class="even">
<td style="text-align: left;">1987 jun</td>
<td style="text-align: right;">230.27</td>
<td style="text-align: right;">329.29</td>
<td style="text-align: right;">-99.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1987 jul</td>
<td style="text-align: right;">254.63</td>
<td style="text-align: right;">348.33</td>
<td style="text-align: right;">-93.70</td>
</tr>
<tr class="even">
<td style="text-align: left;">1987 ago</td>
<td style="text-align: right;">259.14</td>
<td style="text-align: right;">369.38</td>
<td style="text-align: right;">-110.24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1987 set</td>
<td style="text-align: right;">280.55</td>
<td style="text-align: right;">392.97</td>
<td style="text-align: right;">-112.42</td>
</tr>
<tr class="even">
<td style="text-align: left;">1987 out</td>
<td style="text-align: right;">315.35</td>
<td style="text-align: right;">420.56</td>
<td style="text-align: right;">-105.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1987 nov</td>
<td style="text-align: right;">353.27</td>
<td style="text-align: right;">455.26</td>
<td style="text-align: right;">-101.99</td>
</tr>
<tr class="even">
<td style="text-align: left;">1987 dez</td>
<td style="text-align: right;">363.41</td>
<td style="text-align: right;">497.48</td>
<td style="text-align: right;">-134.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1988 jan</td>
<td style="text-align: right;">386.67</td>
<td style="text-align: right;">546.49</td>
<td style="text-align: right;">-159.82</td>
</tr>
<tr class="even">
<td style="text-align: left;">1988 fev</td>
<td style="text-align: right;">399.90</td>
<td style="text-align: right;">601.25</td>
<td style="text-align: right;">-201.35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1988 mar</td>
<td style="text-align: right;">405.18</td>
<td style="text-align: right;">660.97</td>
<td style="text-align: right;">-255.79</td>
</tr>
<tr class="even">
<td style="text-align: left;">1988 abr</td>
<td style="text-align: right;">405.99</td>
<td style="text-align: right;">724.74</td>
<td style="text-align: right;">-318.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1988 mai</td>
<td style="text-align: right;">389.19</td>
<td style="text-align: right;">791.75</td>
<td style="text-align: right;">-402.56</td>
</tr>
<tr class="even">
<td style="text-align: left;">1988 jun</td>
<td style="text-align: right;">398.54</td>
<td style="text-align: right;">861.32</td>
<td style="text-align: right;">-462.78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1988 jul</td>
<td style="text-align: right;">456.52</td>
<td style="text-align: right;">932.73</td>
<td style="text-align: right;">-476.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">1988 ago</td>
<td style="text-align: right;">545.24</td>
<td style="text-align: right;">1005.30</td>
<td style="text-align: right;">-460.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1988 set</td>
<td style="text-align: right;">662.99</td>
<td style="text-align: right;">1078.20</td>
<td style="text-align: right;">-415.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">1988 out</td>
<td style="text-align: right;">761.78</td>
<td style="text-align: right;">1150.68</td>
<td style="text-align: right;">-388.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1988 nov</td>
<td style="text-align: right;">858.09</td>
<td style="text-align: right;">1222.08</td>
<td style="text-align: right;">-363.99</td>
</tr>
<tr class="even">
<td style="text-align: left;">1988 dez</td>
<td style="text-align: right;">980.21</td>
<td style="text-align: right;">1292.11</td>
<td style="text-align: right;">-311.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1989 jan</td>
<td style="text-align: right;">1149.22</td>
<td style="text-align: right;">1360.43</td>
<td style="text-align: right;">-211.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">1989 fev</td>
<td style="text-align: right;">1160.88</td>
<td style="text-align: right;">1426.63</td>
<td style="text-align: right;">-265.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1989 mar</td>
<td style="text-align: right;">1045.29</td>
<td style="text-align: right;">1490.64</td>
<td style="text-align: right;">-445.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">1989 abr</td>
<td style="text-align: right;">940.07</td>
<td style="text-align: right;">1552.74</td>
<td style="text-align: right;">-612.67</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1989 mai</td>
<td style="text-align: right;">944.50</td>
<td style="text-align: right;">1613.17</td>
<td style="text-align: right;">-668.67</td>
</tr>
<tr class="even">
<td style="text-align: left;">1989 jun</td>
<td style="text-align: right;">1001.44</td>
<td style="text-align: right;">1671.94</td>
<td style="text-align: right;">-670.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1989 jul</td>
<td style="text-align: right;">1054.11</td>
<td style="text-align: right;">1728.94</td>
<td style="text-align: right;">-674.83</td>
</tr>
<tr class="even">
<td style="text-align: left;">1989 ago</td>
<td style="text-align: right;">1169.15</td>
<td style="text-align: right;">1784.10</td>
<td style="text-align: right;">-614.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1989 set</td>
<td style="text-align: right;">1269.82</td>
<td style="text-align: right;">1837.19</td>
<td style="text-align: right;">-567.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">1989 out</td>
<td style="text-align: right;">1424.12</td>
<td style="text-align: right;">1888.02</td>
<td style="text-align: right;">-463.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1989 nov</td>
<td style="text-align: right;">1660.95</td>
<td style="text-align: right;">1936.36</td>
<td style="text-align: right;">-275.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">1990 jan</td>
<td style="text-align: right;">2426.12</td>
<td style="text-align: right;">2023.80</td>
<td style="text-align: right;">402.32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1990 fev</td>
<td style="text-align: right;">3701.29</td>
<td style="text-align: right;">2061.35</td>
<td style="text-align: right;">1639.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">1990 mar</td>
<td style="text-align: right;">6390.53</td>
<td style="text-align: right;">2091.54</td>
<td style="text-align: right;">4298.99</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1990 abr</td>
<td style="text-align: right;">6821.31</td>
<td style="text-align: right;">2108.10</td>
<td style="text-align: right;">4713.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">1990 mai</td>
<td style="text-align: right;">6214.99</td>
<td style="text-align: right;">2110.15</td>
<td style="text-align: right;">4104.84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1990 jun</td>
<td style="text-align: right;">5385.43</td>
<td style="text-align: right;">2099.19</td>
<td style="text-align: right;">3286.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">1990 jul</td>
<td style="text-align: right;">4749.03</td>
<td style="text-align: right;">2077.19</td>
<td style="text-align: right;">2671.84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1990 ago</td>
<td style="text-align: right;">3993.62</td>
<td style="text-align: right;">2045.71</td>
<td style="text-align: right;">1947.91</td>
</tr>
<tr class="even">
<td style="text-align: left;">1990 set</td>
<td style="text-align: right;">3304.71</td>
<td style="text-align: right;">2006.60</td>
<td style="text-align: right;">1298.11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1990 out</td>
<td style="text-align: right;">2685.74</td>
<td style="text-align: right;">1961.50</td>
<td style="text-align: right;">724.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">1990 nov</td>
<td style="text-align: right;">2101.34</td>
<td style="text-align: right;">1911.93</td>
<td style="text-align: right;">189.41</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1990 dez</td>
<td style="text-align: right;">1620.97</td>
<td style="text-align: right;">1859.41</td>
<td style="text-align: right;">-238.44</td>
</tr>
<tr class="even">
<td style="text-align: left;">1991 jan</td>
<td style="text-align: right;">1140.27</td>
<td style="text-align: right;">1805.18</td>
<td style="text-align: right;">-664.91</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1991 fev</td>
<td style="text-align: right;">752.02</td>
<td style="text-align: right;">1750.63</td>
<td style="text-align: right;">-998.61</td>
</tr>
<tr class="even">
<td style="text-align: left;">1991 mar</td>
<td style="text-align: right;">422.84</td>
<td style="text-align: right;">1696.96</td>
<td style="text-align: right;">-1274.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1991 abr</td>
<td style="text-align: right;">375.18</td>
<td style="text-align: right;">1645.25</td>
<td style="text-align: right;">-1270.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">1991 mai</td>
<td style="text-align: right;">374.48</td>
<td style="text-align: right;">1595.92</td>
<td style="text-align: right;">-1221.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1991 jun</td>
<td style="text-align: right;">372.10</td>
<td style="text-align: right;">1549.28</td>
<td style="text-align: right;">-1177.18</td>
</tr>
<tr class="even">
<td style="text-align: left;">1991 jul</td>
<td style="text-align: right;">369.96</td>
<td style="text-align: right;">1505.80</td>
<td style="text-align: right;">-1135.84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1991 ago</td>
<td style="text-align: right;">381.41</td>
<td style="text-align: right;">1465.78</td>
<td style="text-align: right;">-1084.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">1991 set</td>
<td style="text-align: right;">386.55</td>
<td style="text-align: right;">1429.29</td>
<td style="text-align: right;">-1042.74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1991 out</td>
<td style="text-align: right;">411.52</td>
<td style="text-align: right;">1396.61</td>
<td style="text-align: right;">-985.09</td>
</tr>
<tr class="even">
<td style="text-align: left;">1991 nov</td>
<td style="text-align: right;">448.31</td>
<td style="text-align: right;">1368.13</td>
<td style="text-align: right;">-919.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1991 dez</td>
<td style="text-align: right;">472.70</td>
<td style="text-align: right;">1344.34</td>
<td style="text-align: right;">-871.64</td>
</tr>
<tr class="even">
<td style="text-align: left;">1992 jan</td>
<td style="text-align: right;">497.32</td>
<td style="text-align: right;">1325.82</td>
<td style="text-align: right;">-828.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1992 fev</td>
<td style="text-align: right;">515.13</td>
<td style="text-align: right;">1313.37</td>
<td style="text-align: right;">-798.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">1992 mar</td>
<td style="text-align: right;">567.21</td>
<td style="text-align: right;">1305.96</td>
<td style="text-align: right;">-738.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1992 abr</td>
<td style="text-align: right;">662.16</td>
<td style="text-align: right;">1302.51</td>
<td style="text-align: right;">-640.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">1992 mai</td>
<td style="text-align: right;">785.81</td>
<td style="text-align: right;">1302.15</td>
<td style="text-align: right;">-516.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1992 jun</td>
<td style="text-align: right;">857.68</td>
<td style="text-align: right;">1304.29</td>
<td style="text-align: right;">-446.61</td>
</tr>
<tr class="even">
<td style="text-align: left;">1992 jul</td>
<td style="text-align: right;">937.94</td>
<td style="text-align: right;">1308.78</td>
<td style="text-align: right;">-370.84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1992 ago</td>
<td style="text-align: right;">996.37</td>
<td style="text-align: right;">1316.53</td>
<td style="text-align: right;">-320.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">1992 set</td>
<td style="text-align: right;">1081.70</td>
<td style="text-align: right;">1330.26</td>
<td style="text-align: right;">-248.56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1992 out</td>
<td style="text-align: right;">1130.94</td>
<td style="text-align: right;">1350.04</td>
<td style="text-align: right;">-219.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">1992 nov</td>
<td style="text-align: right;">1104.20</td>
<td style="text-align: right;">1374.84</td>
<td style="text-align: right;">-270.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1992 dez</td>
<td style="text-align: right;">1119.10</td>
<td style="text-align: right;">1403.63</td>
<td style="text-align: right;">-284.53</td>
</tr>
<tr class="even">
<td style="text-align: left;">1993 jan</td>
<td style="text-align: right;">1161.79</td>
<td style="text-align: right;">1435.50</td>
<td style="text-align: right;">-273.71</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1993 fev</td>
<td style="text-align: right;">1168.49</td>
<td style="text-align: right;">1469.41</td>
<td style="text-align: right;">-300.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">1993 mar</td>
<td style="text-align: right;">1229.71</td>
<td style="text-align: right;">1504.49</td>
<td style="text-align: right;">-274.78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1993 abr</td>
<td style="text-align: right;">1316.42</td>
<td style="text-align: right;">1539.88</td>
<td style="text-align: right;">-223.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">1993 mai</td>
<td style="text-align: right;">1348.52</td>
<td style="text-align: right;">1574.66</td>
<td style="text-align: right;">-226.14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1993 jun</td>
<td style="text-align: right;">1467.33</td>
<td style="text-align: right;">1608.20</td>
<td style="text-align: right;">-140.87</td>
</tr>
<tr class="even">
<td style="text-align: left;">1993 jul</td>
<td style="text-align: right;">1581.70</td>
<td style="text-align: right;">1639.63</td>
<td style="text-align: right;">-57.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1993 ago</td>
<td style="text-align: right;">1730.67</td>
<td style="text-align: right;">1668.21</td>
<td style="text-align: right;">62.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">1993 set</td>
<td style="text-align: right;">1893.13</td>
<td style="text-align: right;">1693.21</td>
<td style="text-align: right;">199.92</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1993 out</td>
<td style="text-align: right;">2031.27</td>
<td style="text-align: right;">1714.18</td>
<td style="text-align: right;">317.09</td>
</tr>
<tr class="even">
<td style="text-align: left;">1993 nov</td>
<td style="text-align: right;">2258.68</td>
<td style="text-align: right;">1730.79</td>
<td style="text-align: right;">527.89</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1993 dez</td>
<td style="text-align: right;">2477.15</td>
<td style="text-align: right;">1742.49</td>
<td style="text-align: right;">734.66</td>
</tr>
<tr class="even">
<td style="text-align: left;">1994 jan</td>
<td style="text-align: right;">2693.84</td>
<td style="text-align: right;">1748.77</td>
<td style="text-align: right;">945.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1994 fev</td>
<td style="text-align: right;">3035.71</td>
<td style="text-align: right;">1749.11</td>
<td style="text-align: right;">1286.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">1994 mar</td>
<td style="text-align: right;">3417.39</td>
<td style="text-align: right;">1742.70</td>
<td style="text-align: right;">1674.69</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1994 abr</td>
<td style="text-align: right;">3828.49</td>
<td style="text-align: right;">1728.68</td>
<td style="text-align: right;">2099.81</td>
</tr>
<tr class="even">
<td style="text-align: left;">1994 mai</td>
<td style="text-align: right;">4331.19</td>
<td style="text-align: right;">1706.10</td>
<td style="text-align: right;">2625.09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1994 jun</td>
<td style="text-align: right;">4922.60</td>
<td style="text-align: right;">1673.80</td>
<td style="text-align: right;">3248.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">1994 jul</td>
<td style="text-align: right;">4005.08</td>
<td style="text-align: right;">1630.39</td>
<td style="text-align: right;">2374.69</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1994 ago</td>
<td style="text-align: right;">3044.89</td>
<td style="text-align: right;">1578.09</td>
<td style="text-align: right;">1466.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">1994 set</td>
<td style="text-align: right;">2253.15</td>
<td style="text-align: right;">1519.23</td>
<td style="text-align: right;">733.92</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1994 out</td>
<td style="text-align: right;">1703.17</td>
<td style="text-align: right;">1455.80</td>
<td style="text-align: right;">247.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">1994 nov</td>
<td style="text-align: right;">1267.54</td>
<td style="text-align: right;">1389.28</td>
<td style="text-align: right;">-121.74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1994 dez</td>
<td style="text-align: right;">916.46</td>
<td style="text-align: right;">1320.77</td>
<td style="text-align: right;">-404.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">1995 jan</td>
<td style="text-align: right;">631.54</td>
<td style="text-align: right;">1251.20</td>
<td style="text-align: right;">-619.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1995 fev</td>
<td style="text-align: right;">426.83</td>
<td style="text-align: right;">1181.32</td>
<td style="text-align: right;">-754.49</td>
</tr>
<tr class="even">
<td style="text-align: left;">1995 mar</td>
<td style="text-align: right;">274.78</td>
<td style="text-align: right;">1111.73</td>
<td style="text-align: right;">-836.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1995 abr</td>
<td style="text-align: right;">169.05</td>
<td style="text-align: right;">1042.83</td>
<td style="text-align: right;">-873.78</td>
</tr>
<tr class="even">
<td style="text-align: left;">1995 mai</td>
<td style="text-align: right;">91.79</td>
<td style="text-align: right;">974.85</td>
<td style="text-align: right;">-883.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1995 jun</td>
<td style="text-align: right;">33.03</td>
<td style="text-align: right;">907.98</td>
<td style="text-align: right;">-874.95</td>
</tr>
<tr class="even">
<td style="text-align: left;">1995 jul</td>
<td style="text-align: right;">27.45</td>
<td style="text-align: right;">842.43</td>
<td style="text-align: right;">-814.98</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1995 ago</td>
<td style="text-align: right;">26.36</td>
<td style="text-align: right;">778.21</td>
<td style="text-align: right;">-751.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">1995 set</td>
<td style="text-align: right;">25.69</td>
<td style="text-align: right;">715.39</td>
<td style="text-align: right;">-689.70</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1995 out</td>
<td style="text-align: right;">24.21</td>
<td style="text-align: right;">654.08</td>
<td style="text-align: right;">-629.87</td>
</tr>
<tr class="even">
<td style="text-align: left;">1995 nov</td>
<td style="text-align: right;">22.59</td>
<td style="text-align: right;">594.33</td>
<td style="text-align: right;">-571.74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1995 dez</td>
<td style="text-align: right;">22.41</td>
<td style="text-align: right;">536.26</td>
<td style="text-align: right;">-513.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">1996 jan</td>
<td style="text-align: right;">21.97</td>
<td style="text-align: right;">480.03</td>
<td style="text-align: right;">-458.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1996 fev</td>
<td style="text-align: right;">21.99</td>
<td style="text-align: right;">425.82</td>
<td style="text-align: right;">-403.83</td>
</tr>
<tr class="even">
<td style="text-align: left;">1996 mar</td>
<td style="text-align: right;">20.55</td>
<td style="text-align: right;">373.80</td>
<td style="text-align: right;">-353.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1996 abr</td>
<td style="text-align: right;">19.17</td>
<td style="text-align: right;">324.15</td>
<td style="text-align: right;">-304.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">1996 mai</td>
<td style="text-align: right;">17.49</td>
<td style="text-align: right;">277.15</td>
<td style="text-align: right;">-259.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1996 jun</td>
<td style="text-align: right;">16.26</td>
<td style="text-align: right;">233.05</td>
<td style="text-align: right;">-216.79</td>
</tr>
<tr class="even">
<td style="text-align: left;">1996 jul</td>
<td style="text-align: right;">14.84</td>
<td style="text-align: right;">192.12</td>
<td style="text-align: right;">-177.28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1996 ago</td>
<td style="text-align: right;">14.21</td>
<td style="text-align: right;">154.76</td>
<td style="text-align: right;">-140.55</td>
</tr>
<tr class="even">
<td style="text-align: left;">1996 set</td>
<td style="text-align: right;">13.26</td>
<td style="text-align: right;">121.44</td>
<td style="text-align: right;">-108.18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1996 out</td>
<td style="text-align: right;">12.02</td>
<td style="text-align: right;">92.64</td>
<td style="text-align: right;">-80.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">1996 nov</td>
<td style="text-align: right;">10.75</td>
<td style="text-align: right;">68.96</td>
<td style="text-align: right;">-58.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1996 dez</td>
<td style="text-align: right;">9.56</td>
<td style="text-align: right;">51.12</td>
<td style="text-align: right;">-41.56</td>
</tr>
<tr class="even">
<td style="text-align: left;">1997 jan</td>
<td style="text-align: right;">9.39</td>
<td style="text-align: right;">38.02</td>
<td style="text-align: right;">-28.63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1997 fev</td>
<td style="text-align: right;">8.82</td>
<td style="text-align: right;">28.52</td>
<td style="text-align: right;">-19.70</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Os outliers são identificados como observações cujo <strong>resíduo da decomposição STL</strong> ultrapassa <span class="math inline">\(3 \times \text{IQR}\)</span> acima do terceiro quartil ou abaixo do primeiro quartil. Esse critério é robusto a não normalidade e captura apenas os desvios verdadeiramente extremos. As observações identificadas correspondem ao período imediatamente pós-Plano Real (1994–1995), quando a inflação acumulada ainda exibia valores muito elevados antes de colapsar rapidamente — um choque estrutural que nenhum modelo autorregressivo consegue capturar adequadamente sem tratamento específico.</p>
<p><strong>Remoção e Interpolação</strong></p>
<p>Os valores identificados como outliers são removidos e substituídos por <code>NA</code>. Em seguida, a função <code>interpolate()</code> utiliza um modelo ARIMA para <strong>imputar os valores ausentes</strong> de forma coerente com a dinâmica da série, ou seja, os valores interpolados são estimativas do que a série teria apresentado naqueles períodos caso não houvesse o choque estrutural. Esse procedimento preserva a continuidade da série e reduz a influência dos valores extremos sobre o ajuste dos modelos subsequentes.</p>
<p><strong>Comparação: Série Original vs.&nbsp;Série Tratada</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/compara-ipca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico sobrepõe a série original (cinza) e a série com outliers interpolados (laranja). As duas curvas são praticamente idênticas ao longo de todo o período, divergindo apenas nos primeiros meses — justamente onde os valores extremos foram substituídos por interpolações mais suaves. Essa intervenção cirúrgica preserva toda a informação histórica relevante do IPCA pós-estabilização, eliminando apenas o impacto desproporcional do choque inflacionário inicial sobre os parâmetros do modelo.</p>
</section>
<section id="previsão-com-tratamento-de-outliers" class="level4" data-number="2.2.12">
<h4 data-number="2.2.12" class="anchored" data-anchor-id="previsão-com-tratamento-de-outliers"><span class="header-section-number">2.2.12</span> Previsão com Tratamento de Outliers</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: ipca 
Model: ARIMA(2,0,1)(0,0,1)[12] w/ mean 

Coefficients:
         ar1      ar2     ma1     sma1  constant
      1.2382  -0.5400  0.8318  -0.0417    6.0766
s.e.  0.0391   0.0389  0.0289   0.0449    4.3365

sigma^2 estimated as 3265:  log likelihood=-2890.5
AIC=5793   AICc=5793.16   BIC=5818.63</code></pre>
</div>
</div>
<p>Com a série tratada, o modelo ARIMA selecionado automaticamente tende a apresentar <strong>ordem de diferenciação menor</strong> (<span class="math inline">\(d = 1\)</span> em vez de <span class="math inline">\(d = 2\)</span>) e estrutura de dependência mais parcimoniosa, refletindo a dinâmica de persistência inflacionária sem a influência distorcida dos outliers. A variância residual (<span class="math inline">\(\sigma^2\)</span>) também deve ser consideravelmente menor, indicando melhor ajuste.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/forecast-final-ipca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Com o tratamento de outliers, as previsões geradas apresentam comportamento bem mais coerente com a dinâmica recente da série: os intervalos de confiança são <strong>substancialmente mais estreitos</strong>, refletindo menor incerteza, e as previsões pontuais acompanham a trajetória inflacionária observada nos últimos anos. A linha vermelha (valores reais do conjunto de teste) encontra-se dentro ou próxima das bandas de confiança, indicando boa calibração do modelo ajustado sobre a série tratada.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Métricas de Acurácia — ARIMA com tratamento de outliers (IPCA)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">RMSE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MAE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MAPE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">auto</td>
<td style="text-align: right;">15.2985</td>
<td style="text-align: right;">14.6964</td>
<td style="text-align: right;">303.1811</td>
<td style="text-align: right;">0.2241</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Em comparação com o modelo ajustado sem tratamento de outliers, as métricas de acurácia melhoram expressivamente após a interpolação. O <strong>MAPE</strong> cai a valores muito menores, refletindo previsões percentualmente mais precisas. O <strong>MASE</strong>, agora inferior a 1, confirma que o modelo ajustado sobre a série tratada <strong>supera a previsão ingênua</strong>, recuperando a capacidade preditiva que havia sido comprometida pelos valores extremos. O <strong>RMSE</strong> e o <strong>MAE</strong> também reduzem, evidenciando menores erros absolutos de previsão em todos os horizontes do conjunto de teste.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto-2_files/figure-html/residuos-final-ipca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Teste de Ljung-Box — Modelo ARIMA final (IPCA tratado)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lb_stat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">auto</td>
<td style="text-align: right;">71.6047</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Com a série tratada, os resíduos do modelo final apresentam comportamento mais próximo do ruído branco.</p>
<hr>
</section>
</section>
</section>
<section id="conclusão" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="conclusão"><span class="header-section-number">3</span> Conclusão</h2>
<p>A análise das duas séries temporais evidenciou como a natureza dos dados — e não apenas a escolha do algoritmo de estimação — determina a adequação do modelo e a qualidade das previsões.</p>
<p>A <strong>série de Consumo nos Lares</strong> apresentou comportamento bem definido: forte sazonalidade de período 12, estacionariedade em nível confirmada pelo KPSS e ausência de tendência de longo prazo. A diferenciação sazonal (<span class="math inline">\(D = 1\)</span>) foi suficiente para tornar a série estacionária, e a comparação por critérios de informação selecionou o modelo SARIMA<span class="math inline">\((0,0,2)(1,1,0)_{12}\)</span> como o mais parcimonioso. O diagnóstico dos resíduos confirmou o adequado ajuste do modelo — com resíduos se comportando como ruído branco tanto visualmente quanto pelo teste de Ljung-Box —, e as previsões reproduziram corretamente o padrão sazonal da série, com MASE inferior a 1, demonstrando superioridade em relação à previsão ingênua.</p>
<p>A <strong>série do IPCA acumulado em 12 meses</strong> revelou complexidade adicional. A presença de valores extremos no início do período — correspondentes ao choque inflacionário do Plano Real — comprometeu o ajuste do modelo ARIMA direto: o melhor candidato pelo AICc exigiu dupla diferenciação (<span class="math inline">\(d = 2\)</span>), apresentou autocorrelação residual significativa (Ljung-Box com p-valor <span class="math inline">\(&lt; 0{,}05\)</span>) e gerou previsões instáveis com intervalos de confiança excessivamente amplos e MASE superior a 1. Esses resultados demonstraram que <strong>critérios de informação como o AICc não são suficientes isoladamente</strong> para validar um modelo — a análise dos resíduos e o comportamento preditivo são etapas indispensáveis.</p>
<p>O tratamento de outliers via decomposição STL e interpolação ARIMA revelou-se a abordagem mais eficaz: ao substituir os valores extremos por estimativas coerentes com a dinâmica da série, foi possível ajustar um modelo mais parcimonioso, com resíduos próximos do ruído branco e previsões consideravelmente mais precisas — MAPE reduzido e MASE inferior a 1. Isso reforça que, em séries econômicas com descontinuidades históricas ou choques estruturais, o pré-processamento adequado dos dados é tão importante quanto a escolha do modelo.</p>
<p>Em síntese, este estudo demonstrou que a modelagem adequada de séries econômicas requer uma abordagem sistemática e crítica, com análise visual, testes formais de estacionariedade, leitura dos correlogramas, seleção por critérios de informação, diagnóstico dos resíduos e avaliação preditiva fora da amostra. A combinação dessas etapas — e não a aplicação mecânica de qualquer método isolado — é o que garante modelos confiáveis e previsões úteis para a tomada de decisão.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="projeto-2_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>